name: "DRINK470"
description: ""

permalink: pretty
baseurl: "/drink470"

permalink: /:categories/:title
maxrating: 5

categories: ["test", "test2", "singles"]

navigation:
    -   title: Drinks
        url: /drinks
    -   title: About
        url: /about

drinks_sub_navigation:
    -  title: Grid
       url: /drinks
    -  title: List
       url: /drinks/list
